crowdfunding/apps/operations/urls.py
from django.conf.urls import url

from operations.views import operation_center, operation_apply, operation_apply_1, operation_member, \
    operation_apply_2, operation_apply_3, operation_apply_4, user_love

urlpatterns = [
    url(r'^operation_center/$',operation_center,name='operation_center'),
    url(r'^operation_member/$',operation_member,name='operation_member'),
    url(r'^operation_apply/$',operation_apply,name='operation_apply'),
    url(r'^operation_apply_1/$',operation_apply_1,name='operation_apply_1'),
    url(r'^operation_apply_2/$',operation_apply_2,name='operation_apply_2'),
    url(r'^operation_apply_3/$',operation_apply_3,name='operation_apply_3'),
    url(r'^operation_apply_4/$',operation_apply_4,name='operation_apply_4'),
    url(r'^user_love/$',user_love,name='user_love'),

]

crowdfunding/apps/projects/urls.py
from django.conf.urls import url
from projects.views import project_detail, project_list, project_start, project_start_step1, project_start_step2, \
    project_start_step3,project_start_step4



urlpatterns = [
    url(r'^project_detail/(\d+)/$',project_detail,name='project_detail'),
    url(r'^project_list/$',project_list,name='project_list'),
    url(r'^project_start/$',project_start,name='project_start'),
    url(r'^project_start_step1/$',project_start_step1,name='project_start_step1'),
    url(r'^project_start_step2/(\d+)/$',project_start_step2,name='project_start_step2'),
    url(r'^project_start_step3/(\d+)/$',project_start_step3,name='project_start_step3'),
    url(r'^project_start_step4/$',project_start_step4,name='project_start_step4'),

]

crowdfunding/crowdfunding/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.users.views import index
import xadmin
from trades.views import alipay

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',index,name='index'),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^projects/',include('projects.urls',namespace='projects')),
    url(r'^operations/',include('operations.urls',namespace='operations')),
    url(r'^trades/',include('trades.urls',namespace='trades')),
    url(r'^alipay/return/', alipay, name="alipay"),
]

crowdfunding/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

crowdfunding/apps/operations/models.py
from django.contrib.auth import get_user_model
from django.db import models
from datetime import datetime
# Create your models here.
from projects.models import Projects
from users.models import UserProfile
#该行代码，是得到系统配置的UserProfi类的实例对象
# UserProfile = get_user_model()

#用户关注的项目
class UserLove(models.Model):
    love_man = models.ForeignKey(UserProfile,verbose_name='关注人')
    love_project = models.ForeignKey(Projects,verbose_name='关注项目')
    love_status = models.BooleanField(default=False,verbose_name='关注状态')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='关注时间')

    def __str__(self):
        return self.love_man.username

    class Meta:
        verbose_name = '关注信息'
        verbose_name_plural = verbose_name


#用户地址
class UserAddress(models.Model):
    user = models.ForeignKey(UserProfile,verbose_name='用户')
    # 用户：user
    # 地址：address
    address = models.CharField(max_length=50,verbose_name='地址')
    # 签收人：singer_name
    signer_name = models.CharField(max_length=30, verbose_name='签收人')
    # 签收电话：singer_mobile
    signer_mobile = models.CharField(max_length=11, verbose_name='签收人电话')
    address_nums = models.IntegerField(default=1,verbose_name='地址数量')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = '用户收货地址'
        verbose_name_plural = verbose_name

crowdfunding/apps/operations/forms.py
from django import forms
from .models import Projects


class OperationApply1Form(forms.Form):
    real_name = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    id_card_num = forms.CharField(required=True)



class OperationApply2Form(forms.Form):
    image = forms.ImageField(required=True)

class OperationApply3Form(forms.Form):
    email = forms.EmailField(required=True)

class OperationApply4Form(forms.Form):
    code = forms.CharField(required=True)

class UserAddressForm(forms.Form):
    address = forms.CharField(required=True)
    signer_name = forms.CharField(required=True)
    signer_mobile = forms.CharField(required=True)

crowdfunding/apps/operations/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect,reverse

# Create your views here.
from helptools.send_email_tools import send_email_code
from operations.forms import OperationApply1Form, OperationApply2Form, OperationApply3Form, OperationApply4Form
# from operations.models import UserProject
from operations.models import UserLove
from projects.models import Projects
from trades.models import UserSupport, OrderInfo
from users.models import VerifyCode, UserProfile


#我的众筹
def operation_center(request):
    user = request.user
    user_projects = Projects.objects.filter(project_man_id=user.id,is_delete=False)
    user_orders = UserSupport.objects.filter(support_man=request.user,is_delete=False)
    user_loves = UserLove.objects.filter(love_man=request.user,love_status=True)
    return render(request, 'operations/operation_center.html',{
        'user_projects':user_projects,
        'user_orders':user_orders,
        'user_loves':user_loves,
        # 'user':user,
    })

#我的资产
def operation_member(request):
    return render(request, 'operations/operation_member.html')



#认证过程
def operation_apply(request):
    return render(request,'operations/operation_apply.html')

def operation_apply_1(request):
    if request.method == 'GET':
        return render(request,'operations/operation_apply_1.html')
    else:
        operation_apply1_form = OperationApply1Form(request.POST)
        if operation_apply1_form.is_valid():
            real_name = operation_apply1_form.cleaned_data['real_name']
            phone = operation_apply1_form.cleaned_data['phone']
            id_card_num = operation_apply1_form.cleaned_data['id_card_num']

            user = request.user
            user.real_name = real_name
            user.phone = phone
            user.id_card_num = id_card_num
            user.save()

            return render(request,'operations/operation_apply_2.html')
        else:
            print('验证出错')
            return render(request,'operations/operation_apply_1.html')


def operation_apply_2(request):
    if request.method == 'GET':
        return render(request,'operations/operation_apply_2.html')
    else:
        operation_apply2_form = OperationApply2Form(request.POST,request.FILES)
        if operation_apply2_form.is_valid():
            image = operation_apply2_form.cleaned_data['image']

            user = request.user
            user.image = image
            user.save()

            return render(request, 'operations/operation_apply_3.html')
        else:
            print('验证出错')
            return render(request, 'operations/operation_apply_2.html')

def operation_apply_3(request):
    if request.method == 'GET':
        return render(request,'operations/operation_apply_3.html')
    else:
        operation_apply3_form = OperationApply3Form(request.POST)
        if operation_apply3_form.is_valid():
            email = operation_apply3_form.cleaned_data['email']

            user = request.user
            user.email = email
            user.save()

            #发送验证码
            send_email_code(email)

            return render(request, 'operations/operation_apply_4.html')
        else:
            print('验证出错')
            return render(request, 'operations/operation_apply_3.html')

def operation_apply_4(request):
    if request.method == 'GET':
        return render(request, 'operations/operation_apply_4.html')
    else:
        operation_apply4_form = OperationApply4Form(request.POST)
        if operation_apply4_form.is_valid():
            code = operation_apply4_form.cleaned_data['code']
            email_ver = VerifyCode.objects.filter(code=code)[0]
            email = email_ver.email
            user = UserProfile.objects.filter(email=email)
            if user:
                user[0].is_verify = True
                user[0].save()
                email_ver.delete()
                return redirect(reverse('operations:operation_center'))
            else:
                return HttpResponse('发送验证码的用户不存在')



        return render(request, 'operations/operation_apply_4.html')


def user_love(request):
    love_id = request.GET.get('love_id', '')

    ty = Projects.objects.filter(id=int(love_id))[0]

    if love_id :
        love = UserLove.objects.filter(love_man=request.user, love_project_id=int(love_id))
        if love:
            if love[0].love_status:
                love[0].love_status = False
                love[0].save()
                ty.love_num -= 1
                ty.save()

                return JsonResponse({'status': 'ok', 'msg': '关注'})
            else:
                love[0].love_status = True
                love[0].save()
                ty.love_num += 1
                ty.save()
                return JsonResponse({'status': 'ok', 'msg': '取消关注'})
        else:
            a = UserLove()
            a.love_man = request.user
            a.love_project_id = love_id
            a.love_status = True
            a.save()
            ty.love_num += 1
            ty.save()
            return JsonResponse({'status': 'ok', 'msg': '取消关注'})
    else:
        return JsonResponse({'status': 'fail', 'msg': '收藏失败'})

crowdfunding/templates/operations/operation_apply_1.html
{% extends 'basic.html' %}
{% load staticfiles %}

{% block mycss %}
<link rel="stylesheet" href="{% static 'css/theme.css' %}">
{% endblock %}

{% block mystyle %}
<style>
			#footer {
				padding: 15px 0;
				background: #fff;
				border-top: 1px solid #ddd;
				text-align: center;
			}
		</style>
{% endblock %}

{% block content %}
		<div class="container theme-showcase" role="main">
			<div class="page-header">
				<h1>实名认证 - 申请</h1>
			</div>

			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a href="#"><span class="badge">1</span> 基本信息</a></li>
				<li role="presentation"><a href="#"><span class="badge">2</span> 资质文件上传</a></li>
				<li role="presentation"><a href="#"><span class="badge">3</span> 邮箱确认</a></li>
				<li role="presentation"><a href="#"><span class="badge">4</span> 申请确认</a></li>
			</ul>

			<form role="form" style="margin-top:20px;" method="post" action="{% url 'operations:operation_apply_1' %}">
                {% csrf_token %}
				<div class="form-group">
					<label for="exampleInputRealname">真实名称</label>
					<input type="text" class="form-control" name="real_name" id="exampleInputRealname" placeholder="请输入真实名称">
				</div>
				<div class="form-group">
					<label for="exampleInputIdcardnum">身份证号码</label>
					<input type="text" class="form-control" name="id_card_num" id="exampleInputIdcardnum" placeholder="请输入身份证号码">
				</div>
				<div class="form-group">
					<label for="exampleInputMobile">电话号码</label>
					<input type="text" class="form-control" name="phone" id="exampleInputMobile" placeholder="请输入电话号码">
				</div>
				<button type="button" onclick="window.location.href='{% url 'operations:operation_apply' %}'" class="btn btn-default">上一步</button>
				<button type="submit" class="btn btn-success">下一步</button>
			</form>
			<hr>
		</div>
		<!-- /container -->
		<div class="container" style="margin-top:20px;">
			<div class="row clearfix">
				<div class="col-md-12 column">
					<div id="footer">
						<div class="footerNav">
							<a rel="nofollow" href="http://www.atguigu.com">关于我们</a> |
							<a rel="nofollow" href="http://www.atguigu.com">服务条款</a> |
							<a rel="nofollow" href="http://www.atguigu.com">免责声明</a> |
							<a rel="nofollow" href="http://www.atguigu.com">网站地图</a> |
							<a rel="nofollow" href="http://www.atguigu.com">联系我们</a>
						</div>
						<div class="copyRight">
							Copyright ?2018-2018atguigu.com 版权所有
						</div>
					</div>

				</div>
			</div>
		</div>
{% endblock %}

crowdfunding/templates/operations/operation_apply_2.html
{% extends 'basic.html' %}
{% load staticfiles %}

{% block mycss %}
<link rel="stylesheet" href="{% static 'css/theme.css' %}">
{% endblock %}

{% block mystyle %}
		<style>
			#footer {
				padding: 15px 0;
				background: #fff;
				border-top: 1px solid #ddd;
				text-align: center;
			}
		</style>
{% endblock %}

{% block content %}
		<div class="container theme-showcase" role="main">
			<div class="page-header">
				<h1>实名认证 - 申请</h1>
			</div>

			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation"><a href="#"><span class="badge">1</span> 基本信息</a></li>
				<li role="presentation" class="active"><a href="#"><span class="badge">2</span> 资质文件上传</a></li>
				<li role="presentation"><a href="#"><span class="badge">3</span> 邮箱确认</a></li>
				<li role="presentation"><a href="#"><span class="badge">4</span> 申请确认</a></li>
			</ul>

			<form role="form" style="margin-top:20px;" enctype="multipart/form-data" method="post" action="{% url 'operations:operation_apply_2' %}">
                {% csrf_token %}
				<div class="form-group">
					<label for="exampleInputIdcardPic">手执身份证照片</label>
					<input type="file" name="image" class="form-control" id="exampleInputIdcardPic">
					<br>
					<img src="{% static 'img/pic.jpg' %}">
				</div>
				<button type="button" onclick="window.location.href='{% url 'operations:operation_apply_1' %}'" class="btn btn-default">上一步</button>
				<button type="submit" class="btn btn-success">下一步</button>
			</form>
			<hr>
		</div>
		<!-- /container -->
		<div class="container" style="margin-top:20px;">
			<div class="row clearfix">
				<div class="col-md-12 column">
					<div id="footer">
						<div class="footerNav">
							<a rel="nofollow" href="http://www.atguigu.com">关于我们</a> |
							<a rel="nofollow" href="http://www.atguigu.com">服务条款</a> |
							<a rel="nofollow" href="http://www.atguigu.com">免责声明</a> |
							<a rel="nofollow" href="http://www.atguigu.com">网站地图</a> |
							<a rel="nofollow" href="http://www.atguigu.com">联系我们</a>
						</div>
						<div class="copyRight">
							Copyright ?2018-2018atguigu.com 版权所有
						</div>
					</div>

				</div>
			</div>
		</div>
{% endblock %}

{% block myjs %}
        <script>
			$('#myTab a').click(function(e) {
				e.preventDefault();
				$(this).tab('show')
			});
		</script>
{% endblock %}

crowdfunding/templates/operations/operation_center.html
{% extends 'basic.html' %}
{% load staticfiles %}
{% block mycss %}
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
{% endblock %}

{% block mystyle %}
    <style>
			#footer {
				padding: 15px 0;
				background: #fff;
				border-top: 1px solid #ddd;
				text-align: center;
			}

			#topcontrol {
				color: #fff;
				z-index: 99;
				width: 30px;
				height: 30px;
				font-size: 20px;
				background: #222;
				position: relative;
				right: 14px !important;
				bottom: 11px !important;
				border-radius: 3px !important;
			}

			#topcontrol:after {
				/*top: -2px;*/
				left: 8.5px;
				content: "\f106";
				position: absolute;
				text-align: center;
				font-family: FontAwesome;
			}

			#topcontrol:hover {
				color: #fff;
				background: #18ba9b;
				-webkit-transition: all 0.3s ease-in-out;
				-moz-transition: all 0.3s ease-in-out;
				-o-transition: all 0.3s ease-in-out;
				transition: all 0.3s ease-in-out;
			}
		</style>
{% endblock %}

{% block content %}

		<div class="container">
			<div class="row clearfix">
				<div class="col-sm-3 col-md-3 column">
					<div class="row">
						<div class="col-md-12">
							<div class="thumbnail" style="    border-radius: 0px;">
								<img src="{{ MEDIA_URL }}{{ request.user.image }}" class="img-thumbnail" alt="A generic square placeholder image with a white border around it, making it resemble a photograph taken with an old instant camera">
								<div class="caption" style="text-align:center;">
									<h3>{{ request.user.username }}</h3>

                                    {% if request.user.is_verify %}
                                        <span class="label label-danger" style="cursor:pointer;">已实名认证</span>
                                    {% else %}
                                        <span class="label label-danger" style="cursor:pointer;" onclick="window.location.href='{% url 'operations:operation_apply' %}'">未实名认证</span>
                                    {% endif %}

								</div>
							</div>
						</div>
					</div>
					<div class="list-group">
						<div class="list-group-item" style="cursor:pointer;" onclick="window.location.href='{% url 'operations:operation_member' %}'">
							资产总览<span class="badge"><i class="glyphicon glyphicon-chevron-right"></i></span>
						</div>
						<div class="list-group-item active">
							我的众筹<span class="badge"><i class="glyphicon glyphicon-chevron-right"></i></span>
						</div>
					</div>
				</div>
				<div class="col-sm-9 col-md-9 column">
					<ul id="myTab" style="" class="nav nav-pills" role="tablist">
						<li role="presentation" class="active">
							<a href="#home" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">我的众筹</a>
						</li>
						<!--<li role="presentation">-->
							<!--<a href="#profile">众筹资产</a>-->
						<!--</li>-->
					</ul>
					<div id="myTabContent" class="tab-content" style="margin-top:10px;">
						<div role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab">

							<ul class="nav nav-tabs myTab1">
								<li role="presentation" class="active"><a href="#support">我支持的</a></li>
								<li role="presentation"><a href="#attension">我关注的</a></li>
								<li role="presentation"><a href="#add">我发起的</a></li>
								<li class=" pull-right"><button type="button" class="btn btn-warning" onclick="window.location.href='{% url 'projects:project_start' %}'">发起众筹</button></li>
							</ul>
							<div class="tab-content myTab1" style="margin-top:10px;">
								<div role="tabpanel" class="tab-pane fade active in" id="support" aria-labelledby="home-tab">
									<div class="container-fluid">
										<div class="row clearfix">
											<div class="col-md-12 column">
												<span class="label label-warning">全部</span> <span class="label" style="color:#000;">已支付</span> <span class="label " style="color:#000;">未支付</span>
											</div>
											<div class="col-md-12 column" style="margin-top:10px;padding:0;">
												<table class="table table-bordered" style="text-align:center;">
													<thead>
														<tr style="background-color:#ddd;">
															<td>项目信息</td>
															<td width="90">支持日期</td>
															<td width="120">支持金额（元）</td>
															<td width="80">回报数量</td>
															<td width="80">交易状态</td>
															<td width="120">操作</td>
														</tr>
													</thead>
													<tbody>

                                                    {% for order in user_orders %}
														<tr>
															<td style="vertical-align:middle;">
																<div class="thumbnail">
																	<div class="caption">
																		<h3>{{ order.support_item.project.name }}</h3>
																		<p>订单编号:{{ order.order_sn }}</p>
																		<p>
																			<div style="float:left;"><i class="glyphicon glyphicon-screenshot" title="目标金额"></i> 已完成 100% </div>
																			<div style="float:right;"><i title="截至日期" class="glyphicon glyphicon-calendar"></i> 剩余8天 </div>
																		</p>
																		<br>
																		<div class="progress" style="margin-bottom: 4px;">
																			<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
																				<span>众筹中</span>
																			</div>
																		</div>
																	</div>
																</div>
															</td>
															<td style="vertical-align:middle;">{{ order.pay_time }}</td>
															<td style="vertical-align:middle;">{{ order.support_item.support_funding }}<br>(运费：{{ order.support_item.transport_cost }})</td>
															<td style="vertical-align:middle;">{{ order.item_nums }}</td>
															<td style="vertical-align:middle;">交易关闭</td>
															<td style="vertical-align:middle;">
																<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
																	<button type="button" class="btn btn-default">删除订单</button>
																</div>
															</td>
														</tr>
                                                    {% endfor %}

													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								<div role="tabpanel" class="tab-pane fade" id="attension" aria-labelledby="attension-tab">
									<div class="container-fluid">
										<div class="row clearfix">
											<div class="col-md-12 column" style="padding:0;">
												<table class="table table-bordered" style="text-align:center;">
													<thead>
														<tr style="background-color:#ddd;">
															<td>项目信息</td>
															<td width="120">支持人数</td>
															<td width="120">关注人数</td>
															<td width="120">操作</td>
														</tr>
													</thead>
													<tbody>
                                                     {% for user_love in user_loves %}
														<tr>
															<td style="vertical-align:middle;">
																<div class="thumbnail">
                                                                    <div class="caption">
																		<p>{{ user_love.love_project.name }}</p>
																		<p><i class="glyphicon glyphicon-jpy"></i> 已筹集 {{ user_love.love_project.support_funding }}元</p>
																		<p>
																			<div style="float:left;"><i class="glyphicon glyphicon-screenshot" title="目标金额"></i> 已完成 {%  widthratio user_love.love_project.support_fund user_love.love_project.target_fund 100 %}% </div>
																			<div style="float:right;"><i class="glyphicon glyphicon-calendar"></i> 剩余2天 </div>
																		</p>
																		<br>
																		<div class="progress" style="margin-bottom: 4px;">
																			<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
																				<span>{{ user_love.love_project.status }}</span>
																			</div>
																		</div>
																	</div>
																</div>
															</td>
															<td style="vertical-align:middle;">{{ user_love.love_project.support_num }}</td>
															<td style="vertical-align:middle;">{{ user_love.love_project.love_num }}</td>
															<td style="vertical-align:middle;">
																<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
																	<button type="button" class="btn btn-default">取消关注</button>
																</div>
															</td>
														</tr>
                                                    {% endfor %}
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								<div role="tabpanel" class="tab-pane fade  " id="add" aria-labelledby="add-tab">
									<div class="container-fluid">
										<div class="row clearfix">
											<div class="col-md-12 column">
												<span class="label label-warning">全部</span> <span class="label" style="color:#000;">众筹中</span> <span class="label " style="color:#000;">众筹成功</span> <span class="label " style="color:#000;">众筹失败</span>
											</div>
											<div class="col-md-12 column" style="padding:0;margin-top:10px;">
												<table class="table table-bordered" style="text-align:center;">
													<thead>
														<tr style="background-color:#ddd;">
															<td>项目信息</td>
															<td width="120">募集金额（元）</td>
															<td width="80">当前状态</td>
															<td width="120">操作</td>
														</tr>
													</thead>
													<tbody>
                                                    {% for project in user_projects %}
														<tr>
															<td style="vertical-align:middle;">
																<div class="thumbnail">
																	<div class="caption">
																		<p>{{ project.name }}</p>
																		<p>
																			<div style="float:left;"><i class="glyphicon glyphicon-screenshot" title="目标金额"></i> 已完成 {%  widthratio project.support_funding project.target_funding 100 %}% </div>
																			<div style="float:right;"><i title="截至日期" class="glyphicon glyphicon-calendar"></i> 剩余8天 </div>
																		</p>
																		<br>
																		<div class="progress" style="margin-bottom: 4px;">
																			<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
																				<span>众筹中</span>
																			</div>
																		</div>
																	</div>
																</div>
															</td>
															<td style="vertical-align:middle;">{{ project.target_funding }}<br>(运费：0.00 )</td>
															<td style="vertical-align:middle;">{% if project_status %}众筹中{% else %}草稿{% endif %}</td>
															<td style="vertical-align:middle;">
																<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
																	<button type="button" class="btn btn-default">项目预览</button>
																	<button type="button" class="btn btn-default">删除项目</button>
																</div>
															</td>
														</tr>
                                                    {% endfor %}
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
							</div>

						</div>
						<div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">
							众筹资产
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container" style="margin-top:20px;">
			<div class="row clearfix">
				<div class="col-md-12 column">
					<div id="footer">
						<div class="footerNav">
							<a rel="nofollow" href="http://www.atguigu.com">关于我们</a> |
							<a rel="nofollow" href="http://www.atguigu.com">服务条款</a> |
							<a rel="nofollow" href="http://www.atguigu.com">免责声明</a> |
							<a rel="nofollow" href="http://www.atguigu.com">网站地图</a> |
							<a rel="nofollow" href="http://www.atguigu.com">联系我们</a>
						</div>
						<div class="copyRight">
							Copyright ?2018-2018atguigu.com 版权所有
						</div>
					</div>

				</div>
			</div>
		</div>
{% endblock %}

{% block myjs %}
		<script>
			$('.myTab a').click(function(e) {
				e.preventDefault()
				$(this).tab('show')
			})
			$('.myTab1 a').click(function(e) {
				e.preventDefault()
				$(this).tab('show')
			})
		</script>
{% endblock %}