crowdfunding/apps/users/urls.py
from django.conf.urls import url
from users.views import user_register,user_login,user_logout


urlpatterns = [
    url(r'^user_register/$',user_register,name='user_register'),
    url(r'^user_login/$',user_login,name='user_login'),
    url(r'^user_logout/$',user_logout,name='user_logout'),
]

crowdfunding/crowdfunding/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.users.views import index
import xadmin
from trades.views import alipay

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',index,name='index'),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^projects/',include('projects.urls',namespace='projects')),
    url(r'^operations/',include('operations.urls',namespace='operations')),
    url(r'^trades/',include('trades.urls',namespace='trades')),
    url(r'^alipay/return/', alipay, name="alipay"),
]

crowdfunding/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

crowdfunding/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
# Create your models here.

class UserProfile(AbstractUser):
    VERIFY_TYPE = (
        (1,'商业公司'),
        (2,'个体工商户'),
        (3,'个人经营'),
        (4,'政府及非营利组织'),
    )

    image = models.ImageField(upload_to='users/%y/%m/%d',max_length=200,verbose_name='用户头像')
    name = models.CharField(max_length=50, verbose_name='姓名', help_text='姓名')
    birthday = models.DateTimeField(null=True,blank=True,verbose_name='用户生日')
    gender = models.CharField(choices=(('男','男'),('女','女')),max_length=10,default='男',verbose_name='性别')
    phone = models.CharField(max_length=11,verbose_name='手机号')
    is_verify = models.BooleanField(default=False,verbose_name='是否认证')
    verify_type = models.CharField(choices=VERIFY_TYPE,max_length=10,verbose_name='认证类型')
    real_name = models.CharField(max_length=20,verbose_name='身份证姓名')
    id_card_num = models.CharField(max_length=18,null=True,blank=True,verbose_name='身份证号')
    id_card_image = models.ImageField(max_length=18,null=True,blank=True,verbose_name='身份证照片')
    email = models.EmailField(max_length=18,null=True,blank=True,verbose_name='邮箱')

    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name


class VerifyCode(models.Model):
    email = models.EmailField(max_length=50,verbose_name='邮箱')
    code = models.CharField(max_length=20,verbose_name='验证码')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = '验证码信息'
        verbose_name_plural = verbose_name

crowdfunding/apps/users/forms.py
from django import forms
from .models import UserProfile


class UserProfileForm(forms.Form):
    name = forms.CharField(required=True,min_length=4,error_messages={
        'required':'用户名必须填写',
        'min_length':'用户名不少于4位',
    })
    password = forms.CharField(required=True,max_length=20, min_length=3, error_messages={
        'required': '密码必须填写',
        'max_length':'密码不超过20位',
        'min_length':'密码不少于3位',
    })
    email = forms.CharField(required=True, min_length=8, error_messages={
        'required': '邮箱必须填写',
        'min_length': '邮箱不少于8位',
    })

class UserLoginForm(forms.Form):
    name = forms.CharField(required=True, min_length=4, error_messages={
        'required': '用户名必须填写',
        'min_length': '用户名不少于4位',
    })
    password = forms.CharField(required=True, max_length=20, min_length=3, error_messages={
        'required': '密码必须填写',
        'max_length': '密码不超过20位',
        'min_length': '密码不少于3位',
    })

crowdfunding/apps/users/views.py
from django.shortcuts import render, redirect,reverse
from django.contrib.auth import authenticate,login,logout
# Create your views here.
from projects.models import IndexCategoryAd, ProjectsCategory, Projects, BannerInfo
from users.forms import UserProfileForm,UserLoginForm
from users.models import UserProfile


def index(request):
    banners = BannerInfo.objects.all().order_by('index')[:3]
    ad_projects = IndexCategoryAd.objects.all().order_by('index')[:3]

    keji_id = ProjectsCategory.objects.filter(name='科技')[0].id
    sheji_id = ProjectsCategory.objects.filter(name='设计')[0].id
    gongyi_id = ProjectsCategory.objects.filter(name='公益')[0].id
    nongye_id = ProjectsCategory.objects.filter(name='农业')[0].id
    keji_projects = Projects.objects.filter(category_id=keji_id)[:4]
    sheji_projects = Projects.objects.filter(category_id=sheji_id)[:4]
    gongyi_projects = Projects.objects.filter(category_id=gongyi_id)[:4]
    nongye_projects = Projects.objects.filter(category_id=nongye_id)[:4]

    return render(request,'index.html',{
        'ad_projects':ad_projects,
        'banners':banners,
        'keji_projects':keji_projects,
        'sheji_projects':sheji_projects,
        'gongyi_projects':gongyi_projects,
        'nongye_projects':nongye_projects,
    })


def user_register(request):
    if request.method == 'GET':
        return render(request, 'users/user_register.html')
    else:
        user_register_form = UserProfileForm(request.POST)
        if user_register_form.is_valid():
            name = user_register_form.cleaned_data['name']
            password = user_register_form.cleaned_data['password']
            email = user_register_form.cleaned_data['email']

            user = UserProfile.objects.filter(username=name)
            if user:
                return render(request,'users/user_register.html',{
                    'msg':'用户名已存在'
                })
            else:
                user = UserProfile()
                user.username = name
                user.name = name
                user.set_password(password)
                user.email = email
                user.save()

                return render(request,'users/user_login.html')
        else:
            return render(request,'users/user_register.html',{
                'user_register_form': user_register_form
            })


def user_login(request):
    if request.method == 'GET':
        return render(request,'users/user_login.html')
    else:
        user_login_form = UserLoginForm(request.POST)
        if user_login_form.is_valid():
            name = user_login_form.cleaned_data['name']
            password = user_login_form.cleaned_data['password']

            user = authenticate(username=name,password=password)
            if user:
                login(request,user)
                return redirect('index')
            else:
                return render(request,'users/user_login.html',{
                    'msg':'用户名或者密码错误'
                })
        else:
            return render(request, 'users/user_login.html', {
                'user_login_form': 'user_login_form'
            })

def user_logout(request):
    logout(request)
    return redirect(reverse('index'))

    ggggg
    yyyyy
    

crowdfunding/templates/users/user_login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">

	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="keys" content="">
		<meta name="author" content="">
		<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/login.css' %}">
		<style>

		</style>
	</head>

	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<div>
						<a class="navbar-brand" href="{% url 'index' %}" style="font-size:32px;">尚筹网-创意产品众筹平台</a>
					</div>
				</div>
			</div>
		</nav>

		<div class="container">

			<form class="form-signin" role="form" method="post" action="{% url 'users:user_login' %}">
                {% csrf_token %}
				<h2 class="form-signin-heading"><i class="glyphicon glyphicon-log-in"></i> 用户登录</h2>
				<div class="form-group has-success has-feedback">
					<input type="text" class="form-control" id="inputSuccessAccount" name="name" placeholder="请输入登录账号" autofocus>
					<span class="glyphicon glyphicon-user form-control-feedback"></span>
				</div>
				<div class="form-group has-success has-feedback">
					<input type="text" class="form-control" id="inputSuccessPassword" name="password" placeholder="请输入登录密码" style="margin-top:10px;">
					<span class="glyphicon glyphicon-lock form-control-feedback"></span>
				</div>
                {{ msg }}
                {% for key,err in user_register_form.errors.items %}
                    {{ err }}
                {% endfor %}
				<div class="checkbox">
					<label><input type="checkbox" value="remember-me"> 记住我</label>
					<br>
					<label>忘记密码</label>
					<label style="float:right"><a href="{% url 'users:user_register' %}">我要注册</a></label>
				</div>
{#				<a class="btn btn-lg btn-success btn-block" onclick="dologin()"> 登录</a>#}
                <input class="btn btn-lg btn-success btn-block" id="jsEmailRegBtn" type="submit" value="登录" />
			</form>
		</div>
	    <script src="{% static 'jquery/jquery-2.1.1.min.js' %}"></script>
		<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
		<script>
			function dologin() {
				var type = $(":selected").val();
				if(type == "user") {
					window.location.href = "main.html";
				} else {
					window.location.href = "index.html";
				}
			}
		</script>
	</body>

</html>

crowdfunding/templates/users/user_register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">

	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="keys" content="">
		<meta name="author" content="">
		<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/login.css' %}">
		<style>

		</style>
	</head>

	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<div>
						<a class="navbar-brand" href="{% url 'index' %}" style="font-size:32px;">尚筹网-创意产品众筹平台</a>
					</div>
				</div>
			</div>
		</nav>

		<div class="container">

			<form class="form-signin" role="form" method="post" action="{% url 'users:user_register' %}">
                {% csrf_token %}
				<h2 class="form-signin-heading"><i class="glyphicon glyphicon-log-in"></i> 用户注册</h2>
				<div class="form-group has-success has-feedback">
					<input type="text" class="form-control" id="inputSuccessAccount" name="name" placeholder="请输入登录账号" autofocus>
					<span class="glyphicon glyphicon-user form-control-feedback"></span>
				</div>
				<div class="form-group has-success has-feedback">
					<input type="text" class="form-control" id="inputSuccessPassword" name="password" placeholder="请输入登录密码" style="margin-top:10px;">
					<span class="glyphicon glyphicon-lock form-control-feedback"></span>
				</div>
				<div class="form-group has-success has-feedback">
					<input type="text" class="form-control" id="inputSuccessEmail" name="email" placeholder="请输入邮箱地址" style="margin-top:10px;">
					<span class="glyphicon glyphicon glyphicon-envelope form-control-feedback"></span>
				</div>
				<div class="form-group has-success has-feedback">
					<select class="form-control">
						<option>企业</option>
						<option>个人</option>
					</select>
				</div>
                {{ msg }}
                {% for key,err in user_register_form.errors.items %}
                    {{ err }}
                {% endfor %}
				<div class="checkbox">
					<label>
            忘记密码
          </label>
					<label style="float:right">
            <a href="{% url 'users:user_login' %}">我有账号</a>
          </label>
				</div>
{#				<a class="btn btn-lg btn-success btn-block" href="{% url 'users:user_register' %}"> 注册</a>#}
                <input class="btn btn-lg btn-success btn-block" id="jsEmailRegBtn" type="submit" value="注册" />

			</form>
		</div>
		<script src="{% static 'jquery/jquery-2.1.1.min.js' %}"></script>
		<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	</body>

</html>