crowdfunding/apps/operations/urls.py
from django.conf.urls import url

from operations.views import operation_center, operation_apply, operation_apply_1, operation_member, \
    operation_apply_2, operation_apply_3, operation_apply_4, user_love

urlpatterns = [
    url(r'^operation_center/$',operation_center,name='operation_center'),
    url(r'^operation_member/$',operation_member,name='operation_member'),
    url(r'^operation_apply/$',operation_apply,name='operation_apply'),
    url(r'^operation_apply_1/$',operation_apply_1,name='operation_apply_1'),
    url(r'^operation_apply_2/$',operation_apply_2,name='operation_apply_2'),
    url(r'^operation_apply_3/$',operation_apply_3,name='operation_apply_3'),
    url(r'^operation_apply_4/$',operation_apply_4,name='operation_apply_4'),
    url(r'^user_love/$',user_love,name='user_love'),

]

crowdfunding/apps/projects/urls.py
from django.conf.urls import url
from projects.views import project_detail, project_list, project_start, project_start_step1, project_start_step2, \
    project_start_step3,project_start_step4



urlpatterns = [
    url(r'^project_detail/(\d+)/$',project_detail,name='project_detail'),
    url(r'^project_list/$',project_list,name='project_list'),
    url(r'^project_start/$',project_start,name='project_start'),
    url(r'^project_start_step1/$',project_start_step1,name='project_start_step1'),
    url(r'^project_start_step2/(\d+)/$',project_start_step2,name='project_start_step2'),
    url(r'^project_start_step3/(\d+)/$',project_start_step3,name='project_start_step3'),
    url(r'^project_start_step4/$',project_start_step4,name='project_start_step4'),

]

crowdfunding/apps/trades/urls.py
from django.conf.urls import url

from trades.views import trade_step1, trade_step2, trade_order,add_address,order_last

urlpatterns = [
    url(r'^trade_step1/(\d+)/$',trade_step1,name='trade_step1'),
    url(r'^trade_step2/(\d+)/$',trade_step2,name='trade_step2'),
    url(r'^trade_order/$',trade_order,name='trade_order'),
    url(r'^add_address/$',add_address,name='add_address'),
    url(r'^order_last/$',order_last,name='order_last'),


]

crowdfunding/apps/users/urls.py
from django.conf.urls import url
from users.views import user_register,user_login,user_logout


urlpatterns = [
    url(r'^user_register/$',user_register,name='user_register'),
    url(r'^user_login/$',user_login,name='user_login'),
    url(r'^user_logout/$',user_logout,name='user_logout'),
]

crowdfunding/crowdfunding/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.users.views import index
import xadmin
from trades.views import alipay

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',index,name='index'),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^projects/',include('projects.urls',namespace='projects')),
    url(r'^operations/',include('operations.urls',namespace='operations')),
    url(r'^trades/',include('trades.urls',namespace='trades')),
    url(r'^alipay/return/', alipay, name="alipay"),
]

crowdfunding/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

crowdfunding/apps/projects/models.py
from django.contrib.auth import get_user_model
from django.db import models
from datetime import datetime
# Create your models here.
from users.models import UserProfile
#该行代码，是得到系统配置的UserProfi类的实例对象
# UserProfile = get_user_model()

#项目类别表
class ProjectsCategory(models.Model):
    name = models.CharField(max_length=30,verbose_name='项目类别名称')
    desc = models.TextField(max_length=100, null=True, blank=True, verbose_name='商品详情', help_text='类别描述')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '项目类别'
        verbose_name_plural = verbose_name


#项目详情
class Projects(models.Model):
    PROJECTSTAUS =(
        ('即将开始','即将开始'),
        ('众筹中','众筹中'),
        ('众筹成功','众筹成功'),
    )
    project_man = models.ForeignKey(UserProfile,null=True,blank=True,verbose_name='项目发起人')
    project_status = models.BooleanField(default=False,verbose_name='项目是否确定发布')
    name = models.CharField(max_length=50,verbose_name='项目名称')

    category = models.ForeignKey(ProjectsCategory,verbose_name='项目类别')
    title_image = models.ImageField(upload_to='projects/%y/%m/%d',max_length=200,verbose_name='项目头图')
    target_funding = models.DecimalField(default=0,max_digits=10,decimal_places=2,verbose_name='筹资金额')
    support_funding = models.DecimalField(default=0,max_digits=10,decimal_places=2,verbose_name='支持金额')
    status = models.CharField(choices=PROJECTSTAUS,max_length=20,default='即将开始',verbose_name='项目状态')
    due_days = models.IntegerField(default=0,verbose_name='筹资天数')
    desc = models.TextField(max_length=100, null=True, blank=True,verbose_name='项目简介')
    detail = models.TextField(max_length=500, null=True, blank=True,verbose_name='项目详情说明')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='发布时间')
    start_time = models.DateTimeField(default=datetime.now,verbose_name='开始时间')
    dead_time = models.DateTimeField(default=datetime.now, verbose_name='截止时间')
    is_delete = models.BooleanField(default=0,verbose_name='是否删除')

    click_num = models.IntegerField(default=0,verbose_name='点击量')
    love_num = models.IntegerField(default=0,verbose_name='关注人数')
    support_num = models.IntegerField(default=0,verbose_name='支持人数')
    user_desc = models.CharField(max_length=50,verbose_name='自我介绍')
    user_detail = models.TextField(max_length=500, null=True, blank=True,verbose_name='详情自我介绍')
    user_mobile = models.CharField(max_length=11,verbose_name='发起人电话')
    service_mobile = models.CharField(max_length=14,verbose_name='客服电话')

    yigou_zhanghao = models.CharField(max_length=18,null=True,blank=True,verbose_name='易付宝企业账号')
    faren_id = models.CharField(max_length=18,null=True,blank=True,verbose_name='法人身份证号')
    is_renzheng = models.BooleanField(default=0,verbose_name='是否认证')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '项目详情'
        verbose_name_plural = verbose_name

#项目详情照片
class ProjectsDetailImage(models.Model):
    project = models.ForeignKey(Projects,verbose_name='项目')
    detail_image = models.ImageField(upload_to='projects/detaili/%y/%m/%d',max_length=200,verbose_name='项目详情图片')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.project.name

    class Meta:
        verbose_name = '项目详情图片'
        verbose_name_plural = verbose_name

#首页广告位
class IndexCategoryAd(models.Model):
    project = models.ForeignKey(Projects,verbose_name='所属项目')
    index = models.IntegerField(default=1, verbose_name='广告项目顺序')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.project.name

    class Meta:
        verbose_name = '首页广告项目'
        verbose_name_plural = verbose_name


#项目可以支持的回报方式
class SupportItems(models.Model):
    SUPPORTSCATEGORY = (
        ('实物回报','实物回报'),
        ('虚拟物品回报','虚拟物品回报')
    )
    project = models.ForeignKey(Projects,verbose_name='所属项目')
    category = models.CharField(choices=SUPPORTSCATEGORY,max_length=20,verbose_name='回报类型')
    support_funding = models.DecimalField(max_digits=8,decimal_places=2,verbose_name='支持金额')
    desc = models.TextField(max_length=200,verbose_name='回报内容')
    image= models.ImageField(upload_to='supports/%y/%m/%d',verbose_name='回报说明图片')
    nums = models.IntegerField(default=0,verbose_name='回报数量')
    supported_nums = models.IntegerField(default=0,verbose_name='此回报已获支持数量')

    is_restrict = models.BooleanField(default=0,verbose_name='是否限购')
    restrict_nums = models.IntegerField(default=1,verbose_name='限购数量')
    transport_cost = models.IntegerField(default=0,verbose_name='运费')
    is_invoice = models.BooleanField(default=0,verbose_name='是否开发票')
    result_time= models.IntegerField(default=0,verbose_name='回报时间')
    is_delete = models.BooleanField(default=0,verbose_name='是否删除')

    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = '回报项目'
        verbose_name_plural = verbose_name


class BannerInfo(models.Model):
    image = models.ImageField(upload_to='banners/%y/%m/%d',max_length=200,verbose_name='首页轮播图片')
    project = models.ForeignKey(Projects,verbose_name='所属项目')
    index = models.IntegerField(default=1, verbose_name='图片顺序')
    url = models.URLField(max_length=200,verbose_name='轮播链接')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name='轮播信息'
        verbose_name_plural = verbose_name

crowdfunding/apps/projects/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect,reverse
from django.core.paginator import PageNotAnInteger,Paginator,EmptyPage
# Create your views here.
# from operations.models import UserProject
from projects.forms import ProjectsForm, SupportItemsForm, Supportstep3Form
from projects.models import Projects, ProjectsCategory, ProjectsDetailImage, SupportItems


def project_list(request):
    all_projects = Projects.objects.all()
    category_all = ProjectsCategory.objects.all()

    search = request.GET.get('search','')
    if search:
        all_projects = all_projects.filter(name__contains=search)

    #根据类别过滤
    cate = request.GET.get('cate','')
    if cate:
        all_projects = all_projects.filter(category_id=int(cate))
    # 根据状态过滤
    stat = request.GET.get('stat','')
    if stat:
        all_projects = all_projects.filter(status=stat)
    # 根据综合过滤
    sort = request.GET.get('sort','')
    if sort == 'time':
        all_projects = all_projects.order_by('-add_time')
    if sort == 'funding':
        all_projects = all_projects.order_by('-target_funding')
    if sort == 'support':
        all_projects = all_projects.order_by('-support_num')



    pa = Paginator(all_projects,4)
    pagenum = request.GET.get('pagenum','')
    try:
        pages = pa.page(pagenum)
    except PageNotAnInteger:
        pages = pa.page(1)
    except EmptyPage:
        pages = pa.page(pa.num_pages)

    return render(request,'projects/project_list.html',{
        'all_projects': all_projects,
        'category_all': category_all,
        'pages': pages,
        'cate': cate,
        'stat': stat,
        'sort': sort,
        'search': search,
    })


def project_detail(request,proid):
    if proid:
        project = Projects.objects.filter(id=proid)[0]
        return render(request,'projects/project_detail.html',{
            'project':project
        })

def project_start(request):
    return  render(request,'projects/project_start.html')


#众筹第一步
def project_start_step1(request):
    if request.method == 'POST':
        project_step1_form = ProjectsForm(request.POST,request.FILES)
        if project_step1_form.is_valid():
            name = project_step1_form.cleaned_data['name']
            title_image = project_step1_form.cleaned_data['title_image']
            detail_image = request.FILES.get('detail_image')
            category = project_step1_form.cleaned_data['category']
            desc = project_step1_form.cleaned_data['desc']
            target_funding = project_step1_form.cleaned_data['target_funding']
            due_days = project_step1_form.cleaned_data['due_days']
            user_detail = project_step1_form.cleaned_data['user_detail']
            user_mobile = project_step1_form.cleaned_data['user_mobile']
            user_desc = project_step1_form.cleaned_data['user_desc']
            service_mobile = project_step1_form.cleaned_data['service_mobile']

            project = Projects()
            project.name = name
            project.title_image = title_image
            project.desc = desc
            project.target_funding = target_funding
            project.due_days = due_days
            project.user_detail = user_detail
            project.user_mobile = user_mobile
            project.user_desc = user_desc
            project.service_mobile = service_mobile
            cate = ProjectsCategory.objects.filter(name=category)[0]
            project.category = cate

            project.save()

            project_detail_image = ProjectsDetailImage()
            project_detail_image.detail_image = detail_image
            project_detail_image.project = project
            project_detail_image.save()

            proid = project.id

            # return render(request,'projects/project_start_step2.html',{
            #     'project':project,
            # })
            #重定向到第二步
            return redirect(reverse('projects:project_start_step2',args=[proid]))
        else:
            return render(request, 'projects/project_start_step1.html', {
                'project_step1_form': project_step1_form
            })
    else:
        category_lists = ProjectsCategory.objects.all()
        return render(request, 'projects/project_start_step1.html', {
            'category_lists': category_lists
        })


#众筹第二步
def project_start_step2(request,proid):
    if proid:
        project = Projects.objects.filter(id=int(proid))[0]
        if request.method == 'GET':
            support_item_lists = SupportItems.objects.filter(project_id=int(proid))
            # support_item_lists = [item.supportitem for item in project_support_lists]
            return render(request, 'projects/project_start_step2.html',{
                'support_item_list':support_item_lists,
                'project':project
            })
        else:
            support_items_form = SupportItemsForm(request.POST,request.FILES)
            if support_items_form.is_valid():
                suppor_funding = support_items_form.cleaned_data['suppor_funding']
                category = support_items_form.cleaned_data['category']
                desc = support_items_form.cleaned_data['desc']
                image = support_items_form.cleaned_data['image']
                nums = support_items_form.cleaned_data['nums']
                is_restrict = support_items_form.cleaned_data['is_restrict']
                restrict_nums = support_items_form.cleaned_data['restrict_nums']
                transport_cost = support_items_form.cleaned_data['transport_cost']
                is_invoice = support_items_form.cleaned_data['is_invoice']
                result_time = support_items_form.cleaned_data['result_time']

                support_item = SupportItems()

                support_item.category = category
                support_item.support_funding = suppor_funding
                support_item.desc = desc
                support_item.image = image
                support_item.nums = nums
                support_item.is_restrict = is_restrict
                support_item.restrict_nums = restrict_nums
                support_item.transport_cost = transport_cost
                support_item.is_invoice = is_invoice
                support_item.result_time = result_time

                support_item.project = project
                support_item.save()

                # project_support = ProjectsSupportItem()
                # project_support.project = project
                # project_support.supportitem = support_item
                # project_support.save()

                proid = project.id

                return redirect(reverse('projects:project_start_step2',args=[proid]))
            else:
                print('验证出错了')
                return redirect(reverse('projects:project_start_step1'))
    else:
        print('没有项目id')
        return redirect(reverse('projects:project_start_step1'))

#众筹第三步
def project_start_step3(request,proid):
    #众筹第三步
    if proid:
        project = Projects.objects.filter(id=int(proid))[0]
        if request.method == 'GET':
            return render(request, 'projects/project_start_step3.html',{
                'project':project
            })
        else:
            support_step3_form = Supportstep3Form(request.POST)
            if support_step3_form.is_valid():
                yigou_zhanghao = support_step3_form.cleaned_data['yigou_zhanghao']
                faren_id =support_step3_form.cleaned_data['faren_id']
                project.yigou_zhanghao = yigou_zhanghao
                project.faren_id = faren_id
                project.project_man = request.user
                project.project_status = True
                project.save()

                return redirect(reverse('projects:project_start_step4'))



def project_start_step4(request):
    return render(request, 'projects/project_start_step4.html')

crowdfunding/templates/projects/project_detail.html
{% extends 'project_basic.html' %}

{% block content1 %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="jumbotron nofollow" style="    padding-top: 10px;">
                <h3>
                {{ project.name }}
            </h3>
                <div style="float:left;width:70%;">
                    {{ project.desc }}
                </div>
                <div style="float:right;">
                    <button type="button" id="lovebtn"  class="btn btn-default"><i style="color:#f60" class="glyphicon glyphicon-heart"></i> <span id="jsRightBtn">关注</span> {{ project.love_num }}</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="row clearfix">
                <div class="col-md-8 column">
                    <img alt="140x140" width="740" src="{{ MEDIA_URL }}{{ project.title_image }}" />
                    {% for image in project.projectsdetailimage_set.all %}
                    <img alt="140x140" width="740" src="{{ MEDIA_URL }}{{ image.detail_image }}" />
                    {% endfor %}

                </div>
                <div class="col-md-4 column">
                    <div class="panel panel-default" style="border-radius: 0px;">
                        <div class="panel-heading" style="background-color: #fff;border-color: #fff;">
                            <span class="label label-success"><i class="glyphicon glyphicon-tag"></i> {{ project.category }}</span>
                        </div>
                        <div class="panel-body">
                            <h3>
                            已筹资金：￥{{ project.support_funding }}
                        </h3>
                            <p><span>目标金额 ： {{ project.target_funding }}</span><span style="float:right;">达成 ： {%  widthratio project.support_funding project.target_funding 100 %}%</span></p>
                            <div class="progress" style="height:10px; margin-bottom: 5px;">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: {%  widthratio project.support_funding project.target_funding 100 %}%;"></div>
                            </div>
                            <p>剩余 {{ project }} 天</p>
                            <div>
                                <p><span>已有{{ project.support_num }}人支持该项目</span></p>
                         <button type="button" class="btn  btn-warning btn-lg btn-block" data-toggle="modal" data-target="#myModal">立即支持</button>
                        </div>
                    </div>
                    <div class="panel-footer" style="    background-color: #fff;
                        border-top: 1px solid #ddd;
                        border-bottom-right-radius: 0px;
                        border-bottom-left-radius: 0px;">
                    <div class="container-fluid">
                        <div class="row clearfix">
                            <div class="col-md-3 column" style="padding:0;">
                    <img alt="140x140" src="img/services-box2.jpg" data-holder-rendered="true" style="width: 80px; height: 80px;">
                    </div>
                    <div class="col-md-9 column">
                        <div class="">
                            <h4>
                                <b>福建省南安厨卫</b> <span style="float:right;font-size:12px;" class="label label-success">已认证</span>
                                    </h4>
                                    <p style="font-size:12px">
                                        酷驰是一家年轻的厨卫科技公司，我们有一支朝气蓬勃，有激情、有想法、敢实践的团队。

                                    </p>
                                    <p style="font-size:12px">
                                        客服电话:0595-86218855
                                    </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% for item in project.supportitems_set.all reversed %}
        <div class="panel panel-default" style="border-radius: 0px;">
            <div class="panel-heading">
                <h3>
                    ￥{{ item.support_funding }}.00 <span style="float:right;font-size:12px;">{% if item.nums == 0 %}无限额{% else %}限额{{ item.nums }}位{% endif %}，{{ item.supported_nums }}位支持者</span>
                </h3>
            </div>
            <div class="panel-body">
                <p>配送费用：{% if item.transport_cost == 0 %}包邮{% else %}邮费{{ item.transport_cost }}元{% endif %}</p>
                <p>预计发放时间：项目筹款成功后的{{ item.result_time }}天内</p>
                <button type="button" class="btn  btn-warning btn-lg" onclick="window.location.href='{% url 'trades:trade_step1' item.id %}'">支持</button>
                <br><br>
                <p>{{ item.desc }}</p>
            </div>
        </div>
        {% endfor %}


        <div class=" panel panel-default" style="border-radius: 0px;">
            <div class="panel-heading">
                <h3>
                    风险提示
                </h3>
            </div>
            <div class="panel-body">
                <p>1.众筹并非商品交易，存在一定风险。支持者根据自己的判断选择、支持众筹项目，与发起人共同实现梦想并获得发起人承诺的回报。<br> 2.众筹平台仅提供平台网络空间及技术支持等中介服务，众筹仅存在于发起人和支持者之间，使用众筹平台产生的法律后果由发起人与支持者自行承担。
                    <br> 3.本项目必须在2017-06-09之前达到￥10000.00 的目标才算成功，否则已经支持的订单将取消。订单取消或募集失败的，您支持的金额将原支付路径退回。<br> 4.请在支持项目后15分钟内付款，否则您的支持请求会被自动关闭。
                    <br> 5.众筹成功后由发起人统一进行发货，售后服务由发起人统一提供；如果发生发起人无法发放回报、延迟发放回报、不提供回报后续服务等情况，您需要直接和发起人协商解决。
                    <br> 6.如您不同意上述风险提示内容，您有权选择不支持；一旦选择支持，视为您已确认并同意以上提示内容。
                </p>
            </div>
        </div>

        <div>
            <h2>为你推荐</h2>
            <hr>
        </div>
        <div class="prjtip panel panel-default" style="border-radius: 0px;">
            <div class="panel-body">
                <img src="img/product-3.png" width="100%" height="100%">
            </div>
        </div>

        <div class="prjtip panel panel-default" style="border-radius: 0px;">
            <div class="panel-body">
                <img src="img/product-4.jpg" width="100%" height="100%">
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% endblock %}

{% block content_detail %}
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<div class="modal-dialog " style="width:960px;height:400px;" role="document">
				<div class="modal-content" data-spy="scroll" data-target="#myScrollspy">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="myModalLabel">选择支持项</h4>
					</div>
					<div class="modal-body">
						<div class="container-fluid">
							<div class="row clearfix">
								<div class="col-sm-3 col-md-3 column" id="myScrollspy">
									<ul class="nav nav-tabs nav-stacked">

                                        {% for foo in project.supportitems_set.all reversed %}
                                        <li class="active">
											<a href="#section-{{ forloop.counter }}">￥{{ foo.support_funding }}</a>
										</li>
                                        {% endfor %}

{#										<li class="active">#}
{#											<a href="#section-1">￥1.00</a>#}
{#										</li>#}
{#										<li class="active">#}
{#											<a href="#section-2">￥149.00</a>#}
{#										</li>#}
{#										<li class="active">#}
{#											<a href="#section-3">￥249.00</a>#}
{#										</li>#}
{#										<li class="active">#}
{#											<a href="#section-4">￥549.00</a>#}
{#										</li>#}
{#										<li class="active">#}
{#											<a href="#section-5">￥1999.00</a>#}
{#										</li>#}
									</ul>
								</div>
								<div id="navList" class="col-sm-9 col-md-9 column" style="height:400px;overflow-y:auto;">

                                    {% for foo in project.supportitems_set.all reversed %}
                                    <h2 id="section-{{ forloop.counter }}" style="border-bottom:1px dashed #ddd;"><span style="font-size:20px;font-weight:bold;">￥{{ foo.support_funding }}</span><span style="font-size:12px;margin-left:60px;">{% if foo.nums == 0 %}无限额{% else %}限额{{ foo.nums }}位{% endif %}，{{ foo.supported_nums }}位支持者</span></h2>
									<p>配送费用：{% if foo.transport_cost == 0 %}全国包邮{% else %}邮费{{ foo.transport_cost }}元{% endif %}</p>
									<p>预计发放时间：项目筹款成功后的{{ foo.result_time }}天内</p>
									<button type="button" class="btn  btn-warning btn-lg " onclick="window.location.href='{% url 'trades:trade_step1' foo.id %}'">支持</button>
									<br><br>
									<p>{{ foo.desc }}</p>
									<hr>
                                    {% endfor %}

{#									<h2 id="section-1" style="border-bottom:1px dashed #ddd;"><span style="font-size:20px;font-weight:bold;">￥1.00</span><span style="font-size:12px;margin-left:60px;">无限额，223位支持者</span></h2>#}
{#									<p>配送费用：全国包邮</p>#}
{#									<p>预计发放时间：项目筹款成功后的30天内</p>#}
{#									<button type="button" class="btn  btn-warning btn-lg " onclick="window.location.href='pay-step-1.html'">支持</button>#}
{#									<br><br>#}
{#									<p>每满1750人抽取一台活性富氢净水直饮机，至少抽取一台。抽取名额（小数点后一位四舍五入）=参与人数÷1750人，由苏宁官方抽取。</p>#}
{#									<hr>#}
{#									<h2 id="section-2" style="border-bottom:1px dashed #ddd;"><span style="font-size:20px;font-weight:bold;">￥149.00</span><span style="font-size:12px;margin-left:60px;">无限额，223位支持者</span></h2>#}
{#									<p>配送费用：全国包邮</p>#}
{#									<p>预计发放时间：项目筹款成功后的30天内</p>#}
{#									<button type="button" class="btn  btn-warning btn-lg " onclick="window.location.href='pay-step-1.html'">支持</button>#}
{#									<br><br>#}
{#									<p>每满1750人抽取一台活性富氢净水直饮机，至少抽取一台。抽取名额（小数点后一位四舍五入）=参与人数÷1750人，由苏宁官方抽取。</p>#}
{#									<hr>#}
{#									<h2 id="section-3" style="border-bottom:1px dashed #ddd;"><span style="font-size:20px;font-weight:bold;">￥249.00</span><span style="font-size:12px;margin-left:60px;">无限额，223位支持者</span></h2>#}
{#									<p>配送费用：全国包邮</p>#}
{#									<p>预计发放时间：项目筹款成功后的30天内</p>#}
{#									<button type="button" class="btn  btn-warning btn-lg " onclick="window.location.href='pay-step-1.html'">支持</button>#}
{#									<br><br>#}
{#									<p>每满1750人抽取一台活性富氢净水直饮机，至少抽取一台。抽取名额（小数点后一位四舍五入）=参与人数÷1750人，由苏宁官方抽取。</p>#}
{#									<hr>#}
{#									<h2 id="section-4" style="border-bottom:1px dashed #ddd;"><span style="font-size:20px;font-weight:bold;">￥549.00</span><span style="font-size:12px;margin-left:60px;">无限额，223位支持者</span></h2>#}
{#									<p>配送费用：全国包邮</p>#}
{#									<p>预计发放时间：项目筹款成功后的30天内</p>#}
{#									<button type="button" class="btn  btn-warning btn-lg " onclick="window.location.href='pay-step-1.html'">支持</button>#}
{#									<br><br>#}
{#									<p>每满1750人抽取一台活性富氢净水直饮机，至少抽取一台。抽取名额（小数点后一位四舍五入）=参与人数÷1750人，由苏宁官方抽取。</p>#}
{#									<hr>#}
{#									<h2 id="section-5" style="border-bottom:1px dashed #ddd;"><span style="font-size:20px;font-weight:bold;">￥1999.00</span><span style="font-size:12px;margin-left:60px;">无限额，223位支持者</span></h2>#}
{#									<p>配送费用：全国包邮</p>#}
{#									<p>预计发放时间：项目筹款成功后的30天内</p>#}
{#									<button type="button" class="btn  btn-warning btn-lg " onclick="window.location.href='pay-step-1.html'">支持</button>#}
{#									<br><br>#}
{#									<p>每满1750人抽取一台活性富氢净水直饮机，至少抽取一台。抽取名额（小数点后一位四舍五入）=参与人数÷1750人，由苏宁官方抽取。</p>#}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

{% block myjs1 %}
<script>
    $(function () {
        $('#lovebtn').click(function () {
            var love_id = {{ project.id }};
            $.ajax({
                type:'GET',
                url:'{% url 'operations:user_love' %}',
                data:{
                    love_id:love_id,
                },
                success:function (callback) {
                    if(callback.status=='ok'){
                        $('#jsRightBtn').text(callback.msg);
                    }else if(callback.status=='fail'){
                        alert(callback.msg)
                    }else{
                        window.location.href='{% url 'users:user_login' %}'
                    }
                }
            })
        })
    })
    </script>
{% endblock %}