crowdfunding/apps/operations/urls.py
from django.conf.urls import url

from operations.views import operation_center, operation_apply, operation_apply_1, operation_member, \
    operation_apply_2, operation_apply_3, operation_apply_4, user_love

urlpatterns = [
    url(r'^operation_center/$',operation_center,name='operation_center'),
    url(r'^operation_member/$',operation_member,name='operation_member'),
    url(r'^operation_apply/$',operation_apply,name='operation_apply'),
    url(r'^operation_apply_1/$',operation_apply_1,name='operation_apply_1'),
    url(r'^operation_apply_2/$',operation_apply_2,name='operation_apply_2'),
    url(r'^operation_apply_3/$',operation_apply_3,name='operation_apply_3'),
    url(r'^operation_apply_4/$',operation_apply_4,name='operation_apply_4'),
    url(r'^user_love/$',user_love,name='user_love'),

]

crowdfunding/apps/projects/urls.py
from django.conf.urls import url
from projects.views import project_detail, project_list, project_start, project_start_step1, project_start_step2, \
    project_start_step3,project_start_step4



urlpatterns = [
    url(r'^project_detail/(\d+)/$',project_detail,name='project_detail'),
    url(r'^project_list/$',project_list,name='project_list'),
    url(r'^project_start/$',project_start,name='project_start'),
    url(r'^project_start_step1/$',project_start_step1,name='project_start_step1'),
    url(r'^project_start_step2/(\d+)/$',project_start_step2,name='project_start_step2'),
    url(r'^project_start_step3/(\d+)/$',project_start_step3,name='project_start_step3'),
    url(r'^project_start_step4/$',project_start_step4,name='project_start_step4'),

]

crowdfunding/crowdfunding/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.users.views import index
import xadmin
from trades.views import alipay

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',index,name='index'),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^projects/',include('projects.urls',namespace='projects')),
    url(r'^operations/',include('operations.urls',namespace='operations')),
    url(r'^trades/',include('trades.urls',namespace='trades')),
    url(r'^alipay/return/', alipay, name="alipay"),
]

crowdfunding/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

crowdfunding/templates/project_basic.html
{% extends 'basic.html' %}
{% load staticfiles %}
{% block mycss %}
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    {% block mycss1 %}
    {% endblock %}
{% endblock %}

{% block mystyle %}
        <style>
			#footer {
				padding: 15px 0;
				background: #fff;
				border-top: 1px solid #ddd;
				text-align: center;
			}

			#topcontrol {
				color: #fff;
				z-index: 99;
				width: 30px;
				height: 30px;
				font-size: 20px;
				background: #222;
				position: relative;
				right: 14px !important;
				bottom: 11px !important;
				border-radius: 3px !important;
			}

			#topcontrol:after {
				/*top: -2px;*/
				left: 8.5px;
				content: "\f106";
				position: absolute;
				text-align: center;
				font-family: FontAwesome;
			}

			#topcontrol:hover {
				color: #fff;
				background: #18ba9b;
				-webkit-transition: all 0.3s ease-in-out;
				-moz-transition: all 0.3s ease-in-out;
				-o-transition: all 0.3s ease-in-out;
				transition: all 0.3s ease-in-out;
			}

			.label-type,
			.label-status,
			.label-order {
				background-color: #fff;
				color: #f60;
				padding: 5px;
				border: 1px #f60 solid;
			}

			#typeList :not(:first-child) {
				margin-top: 20px;
			}

			.label-text {
				margin: 0 10px;
			}

			.panel {
				border-radius: 0;
			}

			h3.break {
				font-size: 16px;
				display: block;
				white-space: nowrap;
				word-wrap: normal;
				overflow: hidden;
				text-overflow: ellipsis;
			}

			h3.break>a {
				text-decoration: none;
			}
		</style>
{% endblock %}


{% block content %}

    <div class="container theme-showcase" role="main">

			<div class="container">
				<div class="row clearfix">
					<div class="col-md-12 column">
						<nav class="navbar navbar-default" role="navigation">
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
								<ul class="nav navbar-nav">
									<li >
										<a rel="nofollow" href="{% url 'index' %}"><i class="glyphicon glyphicon-home"></i> 众筹首页</a>
									</li>
									<li {% if request.path|slice:':22' == '/projects/project_list'  %}class="active"{% endif %}>
										<a rel="nofollow" href="{% url 'projects:project_list' %}"><i class="glyphicon glyphicon-th-large"></i> 项目总览</a>
									</li>
									<li {% if request.path|slice:':22' == '/projects/project_star'  %}class="active"{% endif %}>
										<a rel="nofollow" href="{% url 'projects:project_start' %}"><i class="glyphicon glyphicon-edit"></i> 发起众筹</a>
									</li>
									<li>
										<a rel="nofollow" href="{% url 'operations:operation_center' %}"><i class="glyphicon glyphicon-user"></i> 我的众筹</a>
									</li>
								</ul>
							</div>
						</nav>
					</div>
				</div>
			</div>

    {% block content1 %}
{#            筛选框#}
            <div class="container">
				<div class="row clearfix">
					<div class="col-md-12 column">
						<div class="panel panel-default">
							<div class="panel-body">
								<ul id="typeList" style="list-style: none;">
									<li>
										分类：<span class="label-type actvie">全部</span>
                                        <span class="label-text">科技</span>
                                        <span class="label-text">设计</span>
                                        <span class="label-text">公益</span>
                                        <span class="label-text">农业</span>
                                        <span class="label-text">文化</span>
									</li>
									<li>
										状态：<span class="label-status actvie">全部</span>
                                        <span class="label-text">即将开始</span>
                                        <span class="label-text">众筹中</span>
                                        <span class="label-text">众筹成功</span>
									</li>
									<li>
										排序：<span class="label-order actvie">综合排序</span>
                                        <span class="label-text">最新上线</span>
                                        <span class="label-text">金额最多</span>
                                        <span class="label-text">支持最多</span>
									</li>
								</ul>
							</div>
							<div class="panel-footer" style="height:50px;padding:0;">
								<div style="float:left;padding:15px;">
									共216个众筹项目
								</div>
								<div style="float:right;">
									<form class="navbar-form navbar-left" role="search">
										<div class="form-group">
											<input type="text" class="form-control" placeholder="请输入搜索内容">
										</div>
										<button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i> 搜索</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
{#            列表内容#}
			<div class="container">
				<div class="row clearfix">
					<div class="col-md-12 column">
						<div class="row">

                            {% for project in pages %}
							<div class="col-md-3">
								<div class="thumbnail">
                                    <a href="{% url 'projects:project_detail' project.id %}">
                                    <img alt="300x200" src="{{ MEDIA_URL }}{{ project.title_image }}" />
                                    </a>
									<div class="caption">
										<h3 class="break">
								<a href="{% url 'projects:project_detail' project.id %}">{{ project.name }}</a>
							</h3>
                                <p>
                                    <div style="float:left;"><i class="glyphicon glyphicon-screenshot" title="目标金额"></i> ${{ project.target_funding }} </div>
                                    <div style="float:right;"><i title="截至日期" class="glyphicon glyphicon-calendar"></i> {{ project.dead_time|date:'Y-m-d' }} </div>
                                </p>
                                <br>
                                <div class="progress" style="margin-bottom: 4px;">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                        <span>40% </span>
                                    </div>
                                </div>
                                <div><span style="float:right;"><i class="glyphicon glyphicon-star-empty" ></i></span> <span><i class="glyphicon glyphicon-user" title="支持人数"></i> {{ project.support_num }}</span> </div>
									</div>
								</div>
							</div>
                            {% endfor %}

						</div>

					</div>
				</div>
			</div>
{#            分页#}
			<div class="container">
				<div class="row clearfix">
					<div class="col-md-12 column" style="text-align:center">
						<ul class="pagination">

                        {% if pages.has_previous %}
                        <li><a rel="nofollow" href="?pagenum={{ pages.previous_page_number }}">上一页</a></li>
                            {% else %}
                            <li><a rel="nofollow" href="?pagenum={{ pages.number }}">上一页</a></li>
                        {% endif %}

                        {% for num in pages.paginator.page_range %}
                        <li {% if num == pages.number %} class="active"{% endif %}>
                            <a rel="nofollow" href="?pagenum={{ num }}">{{ num }}</a>
                        </li>
                        {% endfor %}

                        {% if pages.has_next %}
                        <li><a rel="nofollow" href="?pagenum={{ pages.next_page_number }}">下一页</a></li>
                            {% else %}
                            <li><a rel="nofollow" href="?pagenum={{ pages.number }}">下一页</a></li>
                        {% endif %}
						</ul>
					</div>
				</div>
			</div>

    {% endblock %}

{#            页面底部#}
			<div class="container" style="margin-top:20px;">
				<div class="row clearfix">
					<div class="col-md-12 column">
						<div id="footer">
							<div class="footerNav">
								<a rel="nofollow" href="http://www.atguigu.com">关于我们</a> |
								<a rel="nofollow" href="http://www.atguigu.com">服务条款</a> |
								<a rel="nofollow" href="http://www.atguigu.com">免责声明</a> |
								<a rel="nofollow" href="http://www.atguigu.com">网站地图</a> |
								<a rel="nofollow" href="http://www.atguigu.com">联系我们</a>
							</div>
							<div class="copyRight">
								Copyright ?2018-2018atguigu.com 版权所有
							</div>
						</div>

					</div>
				</div>
			</div>

		</div>
    {% block content_detail %}{% endblock %}

{% endblock %}


{% block myjs %}
{% block myjs1 %}{% endblock %}
{% endblock %}